config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'welcome', to: 'welcome#index'
  resources :orders
  resources :castings
  resources :cassettes
  resources :movies
  resources :actors
  resources :categories
  resources :formats
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/casting.rb
class Casting < ApplicationRecord
  belongs_to :actor
  belongs_to :movie
end

app/controllers/castings_controller.rb
class CastingsController < ApplicationController
  before_action :set_casting, only: [:show, :edit, :update, :destroy]

  # GET /castings
  # GET /castings.json
  def index
    @castings = Casting.all
  end

  # GET /castings/1
  # GET /castings/1.json
  def show
  end

  # GET /castings/new
  def new
    @casting = Casting.new
  end

  # GET /castings/1/edit
  def edit
  end

  # POST /castings
  # POST /castings.json
  def create
    @casting = Casting.new(casting_params)

    respond_to do |format|
      if @casting.save
        format.html { redirect_to @casting, notice: 'Casting was successfully created.' }
        format.json { render :show, status: :created, location: @casting }
      else
        format.html { render :new }
        format.json { render json: @casting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /castings/1
  # PATCH/PUT /castings/1.json
  def update
    respond_to do |format|
      if @casting.update(casting_params)
        format.html { redirect_to @casting, notice: 'Casting was successfully updated.' }
        format.json { render :show, status: :ok, location: @casting }
      else
        format.html { render :edit }
        format.json { render json: @casting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /castings/1
  # DELETE /castings/1.json
  def destroy
    @casting.destroy
    respond_to do |format|
      format.html { redirect_to castings_url, notice: 'Casting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casting
      @casting = Casting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def casting_params
      params.require(:casting).permit(:actor_id, :movie_id)
    end
end

app/helpers/castings_helper.rb
module CastingsHelper
end

app/views/castings/_form.html.erb
<%= form_with(model: casting, local: true) do |form| %>
  <% if casting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(casting.errors.count, "error") %> prohibited this casting from being saved:</h2>

      <ul>
      <% casting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :actor_id %>
    <%= form.text_field :actor_id %>
  </div>

  <div class="field">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/castings/edit.html.erb
<h1>Editing Casting</h1>

<%= render 'form', casting: @casting %>

<%= link_to 'Show', @casting %> |
<%= link_to 'Back', castings_path %>

app/views/castings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Castings</h1>

<table>
  <thead>
    <tr>
      <th>Actor</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @castings.each do |casting| %>
      <tr>
        <td><%= casting.actor %></td>
        <td><%= casting.movie %></td>
        <td><%= link_to 'Show', casting %></td>
        <td><%= link_to 'Edit', edit_casting_path(casting) %></td>
        <td><%= link_to 'Destroy', casting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Casting', new_casting_path %>

app/views/castings/new.html.erb
<h1>New Casting</h1>

<%= render 'form', casting: @casting %>

<%= link_to 'Back', castings_path %>

app/views/castings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Actor:</strong>
  <%= @casting.actor %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @casting.movie %>
</p>

<%= link_to 'Edit', edit_casting_path(@casting) %> |
<%= link_to 'Back', castings_path %>