config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'welcome', to: 'welcome#index'
  resources :orders
  resources :castings
  resources :cassettes
  resources :movies
  resources :actors
  resources :categories
  resources :formats
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/format.rb
class Format < ApplicationRecord
end

app/controllers/formats_controller.rb
class FormatsController < ApplicationController
  before_action :set_format, only: [:show, :edit, :update, :destroy]

  # GET /formats
  # GET /formats.json
  def index
    @formats = Format.all
  end

  # GET /formats/1
  # GET /formats/1.json
  def show
  end

  # GET /formats/new
  def new
    @format = Format.new
  end

  # GET /formats/1/edit
  def edit
  end

  # POST /formats
  # POST /formats.json
  def create
    @format = Format.new(format_params)

    respond_to do |format|
      if @format.save
        format.html { redirect_to @format, notice: 'Format was successfully created.' }
        format.json { render :show, status: :created, location: @format }
      else
        format.html { render :new }
        format.json { render json: @format.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formats/1
  # PATCH/PUT /formats/1.json
  def update
    respond_to do |format|
      if @format.update(format_params)
        format.html { redirect_to @format, notice: 'Format was successfully updated.' }
        format.json { render :show, status: :ok, location: @format }
      else
        format.html { render :edit }
        format.json { render json: @format.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formats/1
  # DELETE /formats/1.json
  def destroy
    @format.destroy
    respond_to do |format|
      format.html { redirect_to formats_url, notice: 'Format was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_format
      @format = Format.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def format_params
      params.require(:format).permit(:name)
    end
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/views/formats/_form.html.erb
<%= form_with(model: format, local: true) do |form| %>
  <% if format.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(format.errors.count, "error") %> prohibited this format from being saved:</h2>

      <ul>
      <% format.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formats/edit.html.erb
<h1>Editing Format</h1>

<%= render 'form', format: @format %>

<%= link_to 'Show', @format %> |
<%= link_to 'Back', formats_path %>

app/views/formats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Formats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @formats.each do |format| %>
      <tr>
        <td><%= format.name %></td>
        <td><%= link_to 'Show', format %></td>
        <td><%= link_to 'Edit', edit_format_path(format) %></td>
        <td><%= link_to 'Destroy', format, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Format', new_format_path %>

app/views/formats/new.html.erb
<h1>New Format</h1>

<%= render 'form', format: @format %>

<%= link_to 'Back', formats_path %>

app/views/formats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @format.name %>
</p>

<%= link_to 'Edit', edit_format_path(@format) %> |
<%= link_to 'Back', formats_path %>