config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'welcome', to: 'welcome#index'
  resources :orders
  resources :castings
  resources :cassettes
  resources :movies
  resources :actors
  resources :categories
  resources :formats
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cassette.rb
class Cassette < ApplicationRecord
  belongs_to :movie
  belongs_to :format
end

app/controllers/cassettes_controller.rb
class CassettesController < ApplicationController
  before_action :set_cassette, only: [:show, :edit, :update, :destroy]

  # GET /cassettes
  # GET /cassettes.json
  def index
    @cassettes = Cassette.all
  end

  # GET /cassettes/1
  # GET /cassettes/1.json
  def show
  end

  # GET /cassettes/new
  def new
    @cassette = Cassette.new
  end

  # GET /cassettes/1/edit
  def edit
  end

  # POST /cassettes
  # POST /cassettes.json
  def create
    @cassette = Cassette.new(cassette_params)

    respond_to do |format|
      if @cassette.save
        format.html { redirect_to @cassette, notice: 'Cassette was successfully created.' }
        format.json { render :show, status: :created, location: @cassette }
      else
        format.html { render :new }
        format.json { render json: @cassette.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cassettes/1
  # PATCH/PUT /cassettes/1.json
  def update
    respond_to do |format|
      if @cassette.update(cassette_params)
        format.html { redirect_to @cassette, notice: 'Cassette was successfully updated.' }
        format.json { render :show, status: :ok, location: @cassette }
      else
        format.html { render :edit }
        format.json { render json: @cassette.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cassettes/1
  # DELETE /cassettes/1.json
  def destroy
    @cassette.destroy
    respond_to do |format|
      format.html { redirect_to cassettes_url, notice: 'Cassette was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cassette
      @cassette = Cassette.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cassette_params
      params.require(:cassette).permit(:name, :movie_id, :format_id)
    end
end

app/helpers/cassettes_helper.rb
module CassettesHelper
end

app/views/cassettes/_form.html.erb
<%= form_with(model: cassette, local: true) do |form| %>
  <% if cassette.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cassette.errors.count, "error") %> prohibited this cassette from being saved:</h2>

      <ul>
      <% cassette.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :movie_id %>
    <%= form.text_field :movie_id %>
  </div>

  <div class="field">
    <%= form.label :format_id %>
    <%= form.text_field :format_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cassettes/edit.html.erb
<h1>Editing Cassette</h1>

<%= render 'form', cassette: @cassette %>

<%= link_to 'Show', @cassette %> |
<%= link_to 'Back', cassettes_path %>

app/views/cassettes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cassettes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Movie</th>
      <th>Format</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cassettes.each do |cassette| %>
      <tr>
        <td><%= cassette.name %></td>
        <td><%= cassette.movie %></td>
        <td><%= cassette.format %></td>
        <td><%= link_to 'Show', cassette %></td>
        <td><%= link_to 'Edit', edit_cassette_path(cassette) %></td>
        <td><%= link_to 'Destroy', cassette, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cassette', new_cassette_path %>

app/views/cassettes/new.html.erb
<h1>New Cassette</h1>

<%= render 'form', cassette: @cassette %>

<%= link_to 'Back', cassettes_path %>

app/views/cassettes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cassette.name %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @cassette.movie %>
</p>

<p>
  <strong>Format:</strong>
  <%= @cassette.format %>
</p>

<%= link_to 'Edit', edit_cassette_path(@cassette) %> |
<%= link_to 'Back', cassettes_path %>